name: Test coverage ✅

on:
  pull_request:

jobs:
  coverage:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Generate kover coverage report
        run: ./gradlew koverXmlReportRelease

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/app/build/reports/kover/reportRelease.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          coverage-counter-type: LINE

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: app/build/reports/kover/reportRelease.xml
